import { PrismaClient, Department } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seed REAL MEP projects
 * Run: npx tsx prisma/seed-projects.ts
 */

// All MEP projects categorized by prefix
const projectData = [
    // G - General/Gestión
    { code: 'G-21-901', name: 'Mejoras y Organización' },
    { code: 'G-22-902', name: 'Cursos de formación' },
    { code: 'G-22-903', name: 'Ausencias por Vacaciones/Asuntos Propios/ Bajas' },
    { code: 'G-24-904', name: 'Mejoras y Organización INSTALACIONES' },
    { code: 'G-24-905', name: 'Cursos de formación INSTALACIONES' },

    // O - Ofertas/Licitaciones
    { code: 'O-21-801', name: 'Licitaciones' },
    { code: 'O-21-802', name: 'Ofertas Genéricas' },
    { code: 'O-21-803', name: 'Ofertas Monyma' },
    { code: 'O-21-804', name: 'Ofertas Omexom-Iberdrola' },
    { code: 'O-23-805', name: 'Ofertas Instalaciones 2023' },
    { code: 'O-24-806', name: 'Ofertas Instalaciones 2024' },
    { code: 'O-24-807', name: 'Licitaciones Instalaciones' },

    // P-21 - Proyectos 2021
    { code: 'P-21-021', name: 'I&C Agadir' },
    { code: 'P-21-029', name: 'O&M Pachamama I' },
    { code: 'P-21-030', name: 'EE Regadio Agadir' },
    { code: 'P-21-036', name: 'Kamembe Airport' },
    { code: 'P-21-037', name: 'I&C Taweelah' },
    { code: 'P-21-038', name: 'Fulcrum' },
    { code: 'P-21-042', name: 'Wiring Agadir' },
    { code: 'P-21-043', name: 'PV Vendimia' },
    { code: 'P-21-046', name: 'OS Ayesa AV' },
    { code: 'P-21-047', name: 'Makers' },
    { code: 'P-21-049', name: 'PV Puertollano' },
    { code: 'P-21-050', name: 'I&C Jubail' },
    { code: 'P-21-051', name: 'Fulcrum I&C' },
    { code: 'P-21-052', name: 'Carcel GECI' },
    { code: 'P-21-053', name: 'AY Paquetes' },
    { code: 'P-21-054', name: 'PV Pinal del Rey' },
    { code: 'P-21-055', name: 'AY Out JGF' },
    { code: 'P-21-056', name: 'AY GIS PV Plant' },
    { code: 'P-21-057', name: 'AY Ivirizu' },
    { code: 'P-21-058', name: 'PCI Cooperativa Marismas' },
    { code: 'P-21-059', name: 'AY Surge Tank Al Jubail' },
    { code: 'P-21-060', name: 'HVAC SE-3 y 4' },
    { code: 'P-21-061', name: 'PV Alcon omexom' },
    { code: 'P-21-062', name: 'Subestación Alcon omexom' },
    { code: 'P-21-063', name: 'PV Alconchel omexom' },
    { code: 'P-21-064', name: 'Línea MT Alconchel omexom' },
    { code: 'P-21-065', name: 'PV Proyecto Administrativo' },
    { code: 'P-21-066', name: 'Línea 2020KV Subterranea' },
    { code: 'P-21-067', name: 'RO1 Southern' },
    { code: 'P-21-068', name: 'STP4' },
    { code: 'P-21-069', name: 'Desaladora Barka V' },
    { code: 'P-21-070', name: 'As-Built Control SSEE' },
    { code: 'P-21-071', name: 'Modelos Realidad Aumentada' },
    { code: 'P-21-072', name: 'PFV La Pimienta' },
    { code: 'P-21-073', name: 'PFV Puerto Energy' },
    { code: 'P-21-074', name: 'Ass-Built Control SE Guillena Binudo' },
    { code: 'P-21-075', name: 'Interconexionado PDB SSEE REE' },
    { code: 'P-21-076', name: 'Conexionado Cuadro SSAA SE Las Cabezas' },
    { code: 'P-21-077', name: 'Interconexionado Línea SE Brovales' },
    { code: 'P-21-078', name: 'Cálculos Civiles EDAR Galicia' },
    { code: 'P-21-079', name: 'As-Built Control SSEE 2' },
    { code: 'P-21-080', name: 'LAT Cañuelo I y II' },
    { code: 'P-21-081', name: 'PFV Cañuelo I 40 MW' },
    { code: 'P-21-082', name: 'PFV Cañuelo I I 23 MW' },
    { code: 'P-21-083', name: 'Eiffage Tabernas I y II' },
    { code: 'P-21-083.1', name: 'Ampliación Tabernas' },
    { code: 'P-21-084', name: 'As-Built Control SE Villaguitierrez' },
    { code: 'P-21-085', name: 'Esquemas Interconexión SSEE Ayesa' },
    { code: 'P-21-086', name: 'PFV Rubí II 122 MW (Perú)' },
    { code: 'P-21-086.1', name: 'Ampliación Rubí' },
    { code: 'P-21-087', name: 'As-Built Control SSEE 3' },
    { code: 'P-21-088', name: 'Esquemas de Interconexión SE Eiris' },
    { code: 'P-21-089', name: 'Desaladora Lebrija' },
    { code: 'P-21-090', name: 'Esquemas de Interconexión SE Castrelo' },
    { code: 'P-21-091', name: 'Esquemas de Interconexión Jubail SE-1' },
    { code: 'P-21-092', name: 'As-Built SE Montesa' },
    { code: 'P-21-093', name: 'Esquemas de Interconexión SE Plasencia' },
    { code: 'P-21-094', name: 'LaBe Carta AR' },
    { code: 'P-21-095', name: 'Proyecto Resistencia-Desarrollo RHINONCE' },
    { code: 'P-21-096', name: 'Paquete I&C Layout BIOPOLIS' },
    { code: 'P-21-097', name: 'Modificación PFV Cañuelo I 40 MW' },
    { code: 'P-21-098', name: 'Proyectos Abona' },
    { code: 'P-21-099', name: 'Interconexionado SE Castrelo L Cartelle 1' },
    { code: 'P-21-100', name: 'Interconexionado SE Eliana (L Gaussa 2 + Central)' },
    { code: 'P-21-700', name: 'OS Agadir Regadío AM' },
    { code: 'P-21-701', name: 'OS General Electric JLG' },
    { code: 'P-21-702', name: 'OS Iberdorla MACHU' },
    { code: 'P-21-703', name: 'OS Ayesa RMM' },
    { code: 'P-21-704', name: 'OS Ayesa MA' },
    { code: 'P-21-705', name: 'OS Ayesa AB' },
    { code: 'P-21-706', name: 'OS Ayesa ECH' },
    { code: 'P-21-707', name: 'OS Ayesa JMB' },
    { code: 'P-21-708', name: 'Jubail I&C Apoyo Puntual' },
    { code: 'P-21-709', name: 'SWRO Plant RO1 Actualización P&ID' },
    { code: 'P-21-710', name: 'CANCELADO' },
    { code: 'P-21-711', name: 'Modificación Esquemas SE Guillena Binudo' },
    { code: 'P-21-712', name: 'OS AYESA ECH' },
    { code: 'P-21-713', name: 'AYESA Paquete 1 I&C Revisión de Documentos' },
    { code: 'P-21-714', name: 'OS AYESA EO' },
    { code: 'P-21-715', name: 'OS AYESA MJG' },
    { code: 'P-21-716', name: 'OS AYESA LGR' },
    { code: 'P-21-717', name: 'OS AYESA JLG' },

    // P-22 - Proyectos 2022
    { code: 'P-22-101', name: 'Línea 220 Kv Metaway Ejecutivo' },
    { code: 'P-22-102', name: 'Interconexionado SE Begues 400 kV L Pierola' },
    { code: 'P-22-103', name: 'GSL Proyectos Autoconsumo' },
    { code: 'P-22-104', name: 'Agrofy' },
    { code: 'P-22-105', name: 'PFV Fundación 130MW Colombia' },
    { code: 'P-22-106', name: 'PV Alcón' },
    { code: 'P-22-107', name: 'SE Alcón' },
    { code: 'P-22-108', name: 'PV Alconchel' },
    { code: 'P-22-108.1', name: 'Ampliación PV Alconchel' },
    { code: 'P-22-109', name: 'Línea Alconchel' },
    { code: 'P-22-110', name: 'Interconexionado S.E. Gaussa 400 kV L/Eliana 2' },
    { code: 'P-22-111', name: 'Interconexionado S.E. Begues 400 kV L Espluga' },
    { code: 'P-22-112', name: 'S.E. San Sebastián de los Reyes 400kV, Calle 5, L Loeches 2' },
    { code: 'P-22-113', name: 'Interconexionado S.E. Castrelo 220 kV L/Cartelle 2' },
    { code: 'P-22-114', name: 'Paquete As-Builts Trabajos de mantenimiento' },
    { code: 'P-22-115', name: 'S.E. La Plana 400 kV Pos. GSS2. Renove Este_22' },
    { code: 'P-22-116', name: 'Perfiles Topográficos Pasarela Matalascañas' },
    { code: 'P-22-117', name: 'S.E. Gaussa 400kV PDB' },
    { code: 'P-22-118', name: 'SE SS de los Reyes 400kV Renove 2022' },
    { code: 'P-22-119', name: 'PV Barajas 120 MW' },
    { code: 'P-22-120', name: 'SENS - PV Cabra y Olivar 300MWp' },
    { code: 'P-22-121', name: 'Atarfe I II y III' },
    { code: 'P-22-121.1', name: 'Atarfe I - SE - LAT 220kV' },
    { code: 'P-22-122', name: 'SE ENCE Atarfe 220kV' },
    { code: 'P-22-122.1', name: 'Atarfe II' },
    { code: 'P-22-123', name: 'LAT 220kV Aérea Atarfe' },
    { code: 'P-22-123.1', name: 'Atarfe III' },
    { code: 'P-22-124', name: 'LAT 220kV Subt Atarfe' },
    { code: 'P-22-125', name: 'Interconexionado SE Catadu 400kV Calle 3' },
    { code: 'P-22-126', name: 'Modelado 3D Sistema HVAC Desaladora Jubail' },
    { code: 'P-22-127', name: 'Interconexionado SE Puerto Real 220 kV L/Cartuja' },
    { code: 'P-22-128', name: 'Renovación Sistema de Alerta Hidrológica (SAHBE)' },
    { code: 'P-22-129', name: 'SE Sta Maria 66 kV L Son Orlandis' },
    { code: 'P-22-130', name: 'Interconexionado SE Guillena 400kV Calle 4' },
    { code: 'P-22-131', name: 'Esquemas SET Puebla Magnon' },
    { code: 'P-22-132', name: 'Ingeniería de Ofertas 3 PVs Iberdrola' },
    { code: 'P-22-133', name: 'Interconexionado SE Rocio 220 kV LEvre (L6)' },
    { code: 'P-22-134', name: 'SENS – Oferta PFV Rio Major Portugal' },
    { code: 'P-22-135', name: 'Trabajos Víctor Martínez' },
    { code: 'P-22-136', name: 'BIM PV La Revuelta' },
    { code: 'P-22-137', name: 'Instalaciones Centro de Hípica La Pasión' },
    { code: 'P-22-138', name: 'PFV Elvisa 58 MW Sevilla' },
    { code: 'P-22-139', name: 'Interconexionado SE Guillena 400 kV Calle 8' },
    { code: 'P-22-140', name: 'PS La Cira 56 MW Colombia' },
    { code: 'P-22-141', name: 'Proyecto Const Sistema de Abastecimiento' },
    { code: 'P-22-142', name: 'Ing. De Oferta PV Manztierra 38 MWp' },
    { code: 'P-22-143', name: 'Interconexionado SE Meson Do Vento 220 kV Calle 6' },
    { code: 'P-22-144', name: 'Interconexionado SE Castrelo 220 kV LPazos' },
    { code: 'P-22-145', name: 'Proyecto de Accesos de la PFV Cañuelo I' },
    { code: 'P-22-146', name: 'Interconexionado SE Quintos 220 kV LEvre' },
    { code: 'P-22-147', name: 'PFV Menapy Burgos 12 MWp' },
    { code: 'P-22-718', name: 'OS BOSLAN MACHU SE El Puntal II' },
    { code: 'P-22-719', name: 'OS SIK JLG' },
    { code: 'P-22-720', name: 'OS BOSLAN MACHU SE Villarino' },
    { code: 'P-22-721', name: 'OS CEMOSA SE ALMARAZ JLG' },
    { code: 'P-22-722', name: 'OS CEMOSA SE CASTILBLANCO JLL' },

    // P-23 - Proyectos 2023
    { code: 'P-23-148', name: 'PV El Paso' },
    { code: 'P-23-149', name: 'Interconexionado SE Castellar Fra. 400 kV Calle 4' },
    { code: 'P-23-150', name: 'Desaladora Sousse I&C 50MLD' },
    { code: 'P-23-151', name: 'As-Builts REE' },
    { code: 'P-23-152', name: 'Proyectos Administrativos Alcón' },
    { code: 'P-23-152.1', name: 'Plan de Autoprotección Alcón' },
    { code: 'P-23-153', name: 'SE Rocío 30-66 kV' },
    { code: 'P-23-154', name: 'LAT 66 kV Rocío' },
    { code: 'P-23-155', name: 'Interconexionado SE La Plana 400 kV L.Eliana 1+Central' },
    { code: 'P-23-156', name: 'Ing. de oferta PV Tagus I 115 MWp' },
    { code: 'P-23-157', name: 'Ing. de oferta PV Tagus III 75 MWp' },
    { code: 'P-23-158', name: 'PFV Pepino 20 MW' },
    { code: 'P-23-159', name: 'Earthing Cables HVDC Platform' },
    { code: 'P-23-160', name: 'Ing. Oferta PFV Aeropuerto Tenerife 17 MWp' },
    { code: 'P-23-161', name: 'SE Jumilla-Naturgy' },
    { code: 'P-23-162', name: 'LAT Jumilla 132kV' },
    { code: 'P-23-163', name: 'SE Las Cabras 132kV' },
    { code: 'P-23-164', name: 'PV El Rocío' },
    { code: 'P-23-165', name: 'Ingeniería Oferta PFV Vidigueira' },
    { code: 'P-23-166', name: 'Interconexión SE Eliana 400 kV (Calle 1)' },
    { code: 'P-23-167', name: 'PFV Pepino 3 MW' },
    { code: 'P-23-168', name: 'PFV Villacañas 3 MW' },
    { code: 'P-23-169', name: 'Ing de Oferta PFV Escatrón 50 MW' },
    { code: 'P-23-170', name: 'Ing de Oferta PFV Alhorines 50 MW' },
    { code: 'P-23-171', name: 'PTA Ejecutivo SE Y LAT Cañuelo II' },
    { code: 'P-23-172', name: 'Interconexionado SE Castellar Fra. 400 kV Calle 2' },
    { code: 'P-23-173', name: 'KSA Pumping stations' },
    { code: 'P-23-174', name: 'Modificado PTAD Atarfe I, II y III' },
    { code: 'P-23-175', name: 'PORTOFRIO Centro Logístico Frigorífico' },
    { code: 'P-23-176', name: 'Ingeniería de Tierras Enterradas y Pararrayos' },
    { code: 'P-23-177', name: 'PFV Ende Bolivia' },
    { code: 'P-23-178', name: 'PV Herrera' },
    { code: 'P-23-179', name: 'IWAC – Desaladora Rabigh 4' },
    { code: 'P-23-180', name: 'PTAD Red MT Urbanización' },
    { code: 'P-23-181', name: 'IWAC - Ing. De oferta desaladoras' },
    { code: 'P-23-182', name: 'Serveo – Licitación PV Autoconsumo' },
    { code: 'P-23-183', name: 'Atarfe Ampl. 5' },
    { code: 'P-23-184', name: 'Ampliación Línea Alconchel' },
    { code: 'P-23-185', name: 'Autoconsumo vivienda' },
    { code: 'P-23-186', name: 'Ing. Eléctrica PFV Neosol' },
    { code: 'P-23-187', name: 'Inundaciones LA PASIÓN' },
    { code: 'P-23-188', name: 'PROYECTO COSTE 0' },
    { code: 'P-23-189', name: 'Cálculos LOSA Cimentación Barnience' },
    { code: 'P-23-190', name: 'Procedimiento Interbloqueo STONEWOOD' },
    { code: 'P-23-191', name: 'Estudio Protecciones MT - PFV' },
    { code: 'P-23-723', name: 'OS CEMOSA SE CASTILBLANCO MACHU' },

    // P-24 - Proyectos 2024
    { code: 'P-24-192', name: 'PVF y SET Romeral' },
    { code: 'P-24-193', name: 'IWAC - OS Ingenieía Mecánica' },
    { code: 'P-24-194', name: 'IWAC – OS Ingeniería Mecánica FJMS' },
    { code: 'P-24-195', name: 'CEMOSA - Ingenieria Básica PFV Viru Viru' },
    { code: 'P-24-196', name: 'Justificación Cimentación IPS PFV Pepino' },
    { code: 'P-24-197', name: 'Ampliación BIM PFV Clemesí Rubí' },
    { code: 'P-24-198', name: 'VGE - PFV Peñaflor 120 MW' },
    { code: 'P-24-199', name: 'IWAC - Paquete diseño/3D' },
    { code: 'P-24-200', name: 'DOIT - App Enfermería' },
    { code: 'P-24-201', name: 'VGE – Proyectos PBC' },
    { code: 'P-24-202', name: 'IWAC – Paquete de horas EE' },
    { code: 'P-24-203', name: 'VGE - Parques Eólicos Los Barrios' },
    { code: 'P-24-204', name: 'COXABENGOA – Aavv y EDAR Córdoba' },
    { code: 'P-24-205', name: 'IWAC - Ing. Oferta Desaladora 64 MLDs' },
    { code: 'P-24-206', name: 'IDOM - WWTP Vranishta' },
    { code: 'P-24-207', name: 'IPLAN - Subestacion Benahadux' },
    { code: 'P-24-208', name: 'Incoma - PFV Manzanares 30 MW' },
    { code: 'P-24-209', name: 'Extraco - Inst. Las Cabezas (209)' },
    { code: 'P-24-210', name: 'Alfil - Piso Paseo Marítimo Cádiz (210)' },
    { code: 'P-24-211', name: 'Proyectos Licencias Generales' },
    { code: 'P-24-212', name: 'INCOMA - Estudio BBCC' },
    { code: 'P-24-213', name: 'GSJ - Ing. de oferta PV Garoña' },
    { code: 'P-24-214', name: 'BOZA - Vivienda Bermejales (214)' },
    { code: 'P-24-215', name: 'KLOOS - Chalet Roche (215)' },
    { code: 'P-24-216', name: 'CASTELLANO - 64 viviendas Jerez (216)' },
    { code: 'P-24-217', name: 'ALFIL - Casa Jerez I (217)' },
    { code: 'P-24-218', name: 'GSL – Planes de autoprotección' },
    { code: 'P-24-219', name: 'GSL - PTADs Almacenamiento' },
    { code: 'P-24-220', name: 'VGE - PTA Compás II' },
    { code: 'P-24-221', name: 'IPLAN - Subestación Aljarafe' },
    { code: 'P-24-222', name: 'VGE - PTA Compas I' },
    { code: 'P-24-223', name: 'VGE - PTA Compostilla I' },
    { code: 'P-24-224', name: 'VGE - PTA Compostilla III' },
    { code: 'P-24-225', name: 'SERVEO - Montellano' },
    { code: 'P-24-226', name: 'SERVEO - Benaocaz' },
    { code: 'P-24-227', name: 'SERVEO - Umbrete' },
    { code: 'P-24-228', name: 'SERVEO - Castro del Río' },
    { code: 'P-24-229', name: 'SERVEO - Puerta del Sur' },
    { code: 'P-24-230', name: 'SERVEO - Fuente Amarga' },
    { code: 'P-24-231', name: 'SERVEO - Peñaflor' },
    { code: 'P-24-232', name: 'FEYPE - Proyectos' },
    { code: 'P-24-233', name: 'SERVEO - Constantina' },
    { code: 'P-24-234', name: 'SERVEO - Alcalá de los Gazules' },
    { code: 'P-24-235', name: 'IWAC - Rabigh-4 Iluminación' },
    { code: 'P-24-236', name: 'SERVEO - Bollullos de la Mitación' },
    { code: 'P-24-237', name: 'SERVEO - Corteconcepción - NO VÁLIDO' },
    { code: 'P-24-238', name: 'SERVEO - Real de la Jara' },
    { code: 'P-24-239', name: 'SERVEO - Oficina Marinaleda' },
    { code: 'P-24-240', name: 'SERVEO - Oficina La Campana' },
    { code: 'P-24-241', name: 'SENS – Estudios CDR Pepino 20 y Pepino 3' },
    { code: 'P-24-242', name: 'VGE – Asistencia Técnica SET Pepino' },
    { code: 'P-24-243', name: 'SERVEO - Badolatosa' },
    { code: 'P-24-244', name: 'SERVEO - Algámitas' },
    { code: 'P-24-245', name: 'IASOL – PV Y SET Merinero 37 MW' },
    { code: 'P-24-246', name: 'XAMAI – Estudios Civil PV El Burgo' },
    { code: 'P-24-247', name: 'LICENCIA OFICINAS MEP - LOS REALES' },
    { code: 'P-24-248', name: 'SRASOLAR - Cálculo y camino entronque PFV 52 MWp' },
    { code: 'P-24-249', name: 'SERVEO - Legalizaciones 2024' },
    { code: 'P-24-250', name: 'SERVEO - Coto de Bornos' },
    { code: 'P-24-251', name: 'SRASOLAR – PV CABROVALES 52 MW' },
    { code: 'P-24-252', name: 'INTECSA – Jubail Buraydah WTS phase 2' },
    { code: 'P-24-253', name: 'SAN JOSÉ – Ingeniería de Oferta Jilgueros y Rascón' },
    { code: 'P-24-254', name: 'ML Análisis Video' },
    { code: 'P-24-255', name: 'EIA21 - Estudios Eléctricos Planta Hidrógeno' },
    { code: 'P-24-256', name: 'SERVEO - Clima Adoratrices' },
    { code: 'P-24-257', name: 'SERVEO - Nueva Carteya' },
    { code: 'P-24-258', name: 'GSL – PTAD PV Alconchel' },
    { code: 'P-24-259', name: 'Instalación AA Huberto' },
    { code: 'P-24-260', name: 'SERVEO - Plaza de Andalucía' },
    { code: 'P-24-261', name: 'VGE - PSFV EBORA 34,26 MW' },
    { code: 'P-24-262', name: 'VGE - PSFV ALBERCHE 49,51 MW' },
    { code: 'P-24-263', name: 'IPLAN - SE POLIGONO MT' },
    { code: 'P-24-264', name: 'COXABENGOA - Paquete WAS' },
    { code: 'P-24-265', name: 'GES – Informe SET Calera' },
    { code: 'P-24-266', name: 'GES – Cálculo Térmico LSAT Metaway' },
    { code: 'P-24-267', name: 'GSL – PTAD HIBRIDACIÓN ALCÓN 1' },
    { code: 'P-24-268', name: 'GSL – PTAD HIBRIDACIÓN ALCONCHEL' },
    { code: 'P-24-269', name: 'GSL – PTAD HIBRIDACIÓN ZANCONES' },
    { code: 'P-24-270', name: 'GSL – PTAD HIBRIDACIÓN ARAHAL 1' },
    { code: 'P-24-271', name: 'GSL – PTAD HIBRIDACIÓN JERESOL' },
    { code: 'P-24-272', name: 'SERVEO - Posadas' },
    { code: 'P-24-273', name: 'NAVE ALMACÉN INSTALACIONES' },
    { code: 'P-24-274', name: 'SERVEO - Tocina' },
    { code: 'P-24-275', name: 'Puerto de Sevilla' },
    { code: 'P-24-276', name: 'IDOM – Adec. EDAR Castro-Urdiales' },
    { code: 'P-24-277', name: 'SERVEO - Gilena' },
    { code: 'P-24-278', name: 'ELECAM - Earthing HVDC Platforms' },
    { code: 'P-24-279', name: 'COXABG – C. Hidroeléctrica Salamanca' },
    { code: 'P-24-280', name: 'Logística Instalaciones' },
    { code: 'P-24-281', name: 'SERVEO - Zahara de la Sierra' },
    { code: 'P-24-282', name: 'VGE – Control SET Yebra' },
    { code: 'P-24-283', name: 'SERVEO - Benalup' },
    { code: 'P-24-284', name: 'GSL – PTAD BESS Islas Canarias' },
    { code: 'P-24-285', name: 'AQUATEC – Sist. Distribución de Agua CADASA' },
    { code: 'P-24-286', name: 'INCOMA – Estudio Código de Red PSFV KIWI' },
    { code: 'P-24-287', name: 'IZHARIA – Ing. Detalle SET Pajares Control y SSAA' },
    { code: 'P-24-288', name: 'VGE – Ing. Detalle PFV Las Viñas 44 MWp' },
    { code: 'P-24-289', name: 'GREENING GROUP – Ing. Media Tensión SEAT' },
    { code: 'P-24-290', name: 'SERVEO - Hinojosa del Duque' },
    { code: 'P-24-291', name: 'IWAC– Modelado 3D Edificios Rabighp' },
    { code: 'P-24-292', name: 'GSL– PTAD El Almendro' },
    { code: 'P-24-724', name: 'OS IWAC MSC' },
    { code: 'P-24-725', name: 'OS IWAC FJMS' },
    { code: 'P-24-726', name: 'OS IWAC JVA' },

    // P-25 - Proyectos 2025
    { code: 'P-25-293', name: 'Ing. Detalle P&C SET Alcalá II' },
    { code: 'P-25-294', name: 'SERVEO - Los Rosales' },
    { code: 'P-25-295', name: 'SERVEO - Alanís de la Sierra' },
    { code: 'P-25-296', name: 'COX - Ampliación Paquete WAS I&C' },
    { code: 'P-25-297', name: 'GSJ – Ing. Oferta PV Villena 113 MWp' },
    { code: 'P-25-298', name: 'GSL – Ing. Detalle PV Jerezol 0,8 MW' },
    { code: 'P-25-299', name: 'GSL – PTAD Mijas' },
    { code: 'P-25-300', name: 'BOSLAN – SET Palencia' },
    { code: 'P-25-301', name: 'SERVEO - Corteconcepción' },
    { code: 'P-25-302', name: 'SERVEO - Villarrasa' },
    { code: 'P-25-303', name: 'ADENTECH – Cálculo SKID' },
    { code: 'P-25-304', name: 'SERVEO - Santiponce' },
    { code: 'P-25-305', name: 'SERVEO - Puebla de Cazalla' },
    { code: 'P-25-306', name: 'SRA – PVs Torozos I II y III' },
    { code: 'P-25-307', name: 'AURINKA – Cálculo PaT PV Greencar 1' },
    { code: 'P-25-308', name: 'VGE – SET Rocío Coordinación Protecciones' },
    { code: 'P-25-309', name: 'CEMOSA – Ampliación BIM Fundación' },
    { code: 'P-25-310', name: 'SERVEO - Rute' },
    { code: 'P-25-311', name: 'SERVEO - Higuera de la Sierra' },
    { code: 'P-25-312', name: 'CEMOSA – Planos Mov. Tierras PV' },
    { code: 'P-25-313', name: 'TEXLA – Concesión Aguas Planta H2' },
    { code: 'P-25-314', name: 'SERVEO - AV. Del Tejar (Pto. Sta. Mª)' },
    { code: 'P-25-315', name: 'SIK - Hospital Honduras' },
    { code: 'P-25-316', name: 'SUNAN – Ing. Detalle LAAT 220 kV Gamudejar' },
    { code: 'P-25-317', name: 'SARPEL – Ing. Detalle SET Vilecha 400 kV' },
    { code: 'P-25-318', name: 'GSL - PTAD BESS Amate' },
    { code: 'P-25-319', name: 'GESTUT - Centro Ecuestre El Juncal' },
    { code: 'P-25-320', name: 'FANY - Instalación placas solares' },
    { code: 'P-25-321', name: 'SERVEO - Santa Clara de Cuba' },
    { code: 'P-25-322', name: 'CEMOSA – Hibridación 3 PV' },
    { code: 'P-25-323', name: 'CEMOSA – Estudio Hidrológico PV Arjona' },
    { code: 'P-25-324', name: 'INGNOVA – Estudio Campos Magnéticos' },
    { code: 'P-25-325', name: 'SUEZ – Paquete de horas Ing. Eléctrico e I&C' },
    { code: 'P-25-326', name: 'TPF – Ingeniería EE e I&C Planta Tratamiento Terciario' },
    { code: 'P-25-327', name: 'ROMAN ARQUITECTO - Piso Sevilla plaza de Cuba' },
    { code: 'P-25-328', name: 'PRODIEL - Comprobaciones Térmicas Zanjas' },
    { code: 'P-25-329', name: 'SENER - Ing. Oferta Túneles y Bombeo, Dubai' },
    { code: 'P-25-330', name: 'REBECA - Instalación Aire acondicionado' },
    { code: 'P-25-331', name: 'GESTUT - Reforma de Instalaciones el Juncal' },
    { code: 'P-25-332', name: 'CEMOSA - Comprobaciones Térmicas Zanjas' },
    { code: 'P-25-333', name: 'AURINKA - Comprobaciones Térmicas Zanjas Greencar' },
    { code: 'P-25-334', name: 'AYESA - Estudio PaT PV 250 MW' },
    { code: 'P-25-335', name: 'SERVEO - Alcosa' },
    { code: 'P-25-336', name: 'DRAGADOS – Servicios Delineación I&C' },
    { code: 'P-25-337', name: 'ORTOPEDIA G.L. – Licencia de actividad y cambio de uso' },
    { code: 'P-25-338', name: 'SARPEL – Ing. MT SE Higo y SE Changuiniola' },
    { code: 'P-25-339', name: 'SARPEL – Ing. MT SE La Floresta' },
    { code: 'P-25-340', name: 'ROSENDO - Instalación Climatización' },
    { code: 'P-25-341', name: 'TM Guadalquivir - Puerto Sevilla - Trabajos varios' },
    { code: 'P-25-342', name: 'RAQUEL MONTALBÁN - Licencia ambigú Chipiona' },
    { code: 'P-25-343', name: 'SARPEL – Ing. Detalle SET Vilecha 132 kV' },
    { code: 'P-25-344', name: 'MERCEDES - Instalación Aire acondicionado' },
    { code: 'P-25-345', name: 'SARPEL – Esquemas Cuadros y Armarios' },
    { code: 'P-25-346', name: 'PROCESSITE – Inf. Elec. Desaladora Tordera' },
    { code: 'P-25-347', name: 'SERVEO - Virgen de Luján' },
    { code: 'P-25-348', name: 'SERVEO - Córdoba' },
    { code: 'P-25-349', name: 'SERVEO - Centro de empresas (Jerez) - ANULADA (365)' },
    { code: 'P-25-350', name: 'ALBERTO - Trajano' },
    { code: 'P-25-351', name: 'SERVEO - Jesús Rescatado' },
    { code: 'P-25-352', name: 'SERVEO – Memoria PV Marquesinas' },
    { code: 'P-25-353', name: 'SERVEO - Suministro Rejas Fachadas' },
    { code: 'P-25-354', name: 'SERVEO - Legalizaciones 2025' },
    { code: 'P-25-355', name: 'ORTOPEDIA GERARDO LEÓN - Reforma Ortopedia y CAIT' },
    { code: 'P-25-356', name: 'GSL - PTAD BESS Fuengirola' },
    { code: 'P-25-357', name: 'COX - Estudios EE WAS' },
    { code: 'P-25-358', name: 'IZHARIA – Ing. Detalle LSAT 132 kV' },
    { code: 'P-25-359', name: 'ORYX – Subsanación PV Arganda Solar II' },
    { code: 'P-25-360', name: 'ELECAM – Ampliación Estudio PaT Plataforma' },
    { code: 'P-25-361', name: 'SERVEO - Condensación Sierpes' },
    { code: 'P-25-362', name: 'ELMYA – Estudio Coordinación Prot. 2 PFV y SET' },
    { code: 'P-25-363', name: 'SRA – MdT PFV Kanazawa' },
    { code: 'P-25-364', name: 'SRA – MdT PFV Shin Berkeley' },
    { code: 'P-25-365', name: 'SERVEO - Jerez de la Frontera_Mamelon' },
    { code: 'P-25-366', name: 'SERVEO - Ampliación HUBS CÓRDOBA' },
    { code: 'P-25-367', name: 'USTOM - 14 apartamentos Calle San Luis' },
    { code: 'P-25-368', name: 'SERVEO - Oficina DAN Huelva Andévalo' },
    { code: 'P-25-369', name: 'SERVEO - Oficina Cala' },
    { code: 'P-25-370', name: 'SRA - MdT PFV BLUE LINE' },
    { code: 'P-25-371', name: 'SRA - MdT PFV OOKA' },
    { code: 'P-25-372', name: 'SERVEO - Oficina El Granado' },
    { code: 'P-25-373', name: 'SERVEO - Oficina El Bosque' },
    { code: 'P-25-374', name: 'GESNAER - Aerotermia T2 BCN' },
    { code: 'P-25-375', name: 'SERVEO - Nueva Sevilla' },
    { code: 'P-25-376', name: 'PRODIEL – Cálculos Térmicos Brazatortas' },
    { code: 'P-25-377', name: 'VINCI – Estudio Coord. Prot. IRON y CLAVE' },
    { code: 'P-25-378', name: 'VGE – Centro Seccionamiento Bluesol' },
    { code: 'P-25-379', name: 'SERVEO – Bankinter Mairena del Aljarafe' },
    { code: 'P-25-380', name: 'TPF – EDAR Isla Baja' },
    { code: 'P-25-381', name: 'IV - HV Cable Thermal Studies' },
    { code: 'P-25-382', name: 'SERVEO - Almadén de la Plata' },
    { code: 'P-25-383', name: 'SERVEO - Cabezas Rubias' },
    { code: 'P-25-384', name: 'IWAC- Ing. Oferta HVAC & FF' },
    { code: 'P-25-385', name: 'VINCI – Cálculo Térmico IRON y CLAVE' },
    { code: 'P-25-386', name: 'GSL – PTAD SET Miraflores' },
    { code: 'P-25-387', name: 'FRAN – Instalación PV autoconsumo' },
    { code: 'P-25-388', name: 'JUAN DIEGO ARAGON - Caldera Chalet Conil' },
    { code: 'P-25-389', name: 'JUAN OJEDA - Instalación de equipos' },
    { code: 'P-25-390', name: 'OFICINA CENTRO - Reforma' },
    { code: 'P-25-391', name: 'ELEVEN VIEWS - Licencia bar-cocina' },
    { code: 'P-25-392', name: 'FERROVIAL – Cálculo galería MT Chile' },
    { code: 'P-25-393', name: 'FELIPE CASTELLANO – Afanas Chiclana' },
    { code: 'P-25-394', name: 'INTECSA – Proyecto Parking Tenerife Norte' },
    { code: 'P-25-395', name: 'ASCH – Proyecto Marquesinas PV y BESS' },
    { code: 'P-25-396', name: 'MAYTE AYALA – Lavabos' },
    { code: 'P-25-397', name: 'BUTANO LEVANTE - Instalaciones de Enlace' },
    { code: 'P-25-398', name: 'GSL - PTAD SET Cortijo Colorado' },
    { code: 'P-25-399', name: 'GSL - PTAD SET Benalmádena' },

    // P-26 - Proyectos 2026
    { code: 'P-26-400', name: 'ÁTICO REALES - Aires acondicionados' },
    { code: 'P-26-401', name: 'LANTANIA - PTR Al Badaa' },
    { code: 'P-26-402', name: 'ROMÁN GARCÍA - Suelo radiante Polonia 5' },
    { code: 'P-26-403', name: 'GSL - PTAD SET Montes' },
    { code: 'P-26-404', name: 'GRUPO COBRA - Las Albinas Chiclana' },
    { code: 'P-26-405', name: 'GSL - PTAD SET MARYSOL' },
    { code: 'P-26-406', name: 'GSL - PTAD SET MANANTIALES' },
    { code: 'P-26-407', name: 'STAR SOLUTIONS - Gravina' },
    { code: 'P-26-408', name: 'STAR SOLUTIONS - Reparaciones Calle Velarde' },
    { code: 'P-26-409', name: 'INERCO - Ing. Oferta PTA ZLD' },
];

/**
 * Get year from project code
 */
function getYearFromCode(code: string): number {
    const parts = code.split('-');
    if (parts.length >= 2) {
        const yearPart = parts[1];
        if (yearPart.length === 2) {
            return 2000 + parseInt(yearPart);
        }
    }
    return 2024; // default
}

/**
 * Get department based on project type
 */
function getDepartment(name: string): Department {
    const nameLower = name.toLowerCase();
    if (nameLower.includes('instalacion') || nameLower.includes('clima') || nameLower.includes('hvac') || nameLower.includes('aire')) {
        return Department.OTHER;
    }
    if (nameLower.includes('electrical') || nameLower.includes('se ') || nameLower.includes('set ') || nameLower.includes('subestacion') || nameLower.includes('lat ') || nameLower.includes('linea') || nameLower.includes('mt ') || nameLower.includes('kv')) {
        return Department.ELECTRICAL;
    }
    if (nameLower.includes('i&c') || nameLower.includes('control') || nameLower.includes('p&id')) {
        return Department.INSTRUMENTATION;
    }
    if (nameLower.includes('pv ') || nameLower.includes('pfv ') || nameLower.includes('solar') || nameLower.includes('fotovoltaic')) {
        return Department.ELECTRICAL;
    }
    return Department.CIVIL_DESIGN;
}

async function main() {
    console.log('🌱 Seeding MEP Projects...\n');

    // Get company
    const company = await prisma.company.findFirst({ where: { slug: 'mep-projects' } });
    if (!company) throw new Error('Company not found. Run seed-users.ts first.');

    // Clean old projects
    console.log('🗑️ Cleaning old projects...');
    await prisma.timeEntry.deleteMany();
    await prisma.task.deleteMany();
    await prisma.project.deleteMany();
    console.log('✅ Old projects cleaned\n');

    // Create projects
    console.log('📁 Creating projects...');
    let created = 0;

    for (const p of projectData) {
        try {
            await prisma.project.create({
                data: {
                    code: p.code,
                    name: p.name,
                    year: getYearFromCode(p.code),
                    department: getDepartment(p.name),
                    company: { connect: { id: company.id } },
                }
            });
            created++;
        } catch (e: any) {
            console.log(`⚠️ Skipped ${p.code}: ${e.message?.slice(0, 50) || 'Error'}`);
        }
    }

    console.log(`\n✅ ${created} projects created!`);
    console.log(`\n📊 Run: npx tsx prisma/seed-projects.ts`);
}

main()
    .catch((e) => { console.error('❌ Error:', e); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); });
